#install.packages("survminer")
#install.packages("survival")
library(survival)
library(survminer)

df1 = read.table("4_1_1.txt", header = 1)
df1$Time = as.numeric(df1$Time)
fit = survfit(Surv(Time,censor) ~ Group, data = df1)
pv = survminer::surv_pvalue(fit, data = df1)[2]
df1.survdiff = survdiff(Surv(Time,censor) ~ Group, data = df1)
p.val = 1 - pchisq(df1.survdiff$chisq, length(df1.survdiff$n) - 1)
HR = (df1.survdiff$obs[2]/df1.survdiff$exp[2])/(df1.survdiff$obs[1]/df1.survdiff$exp[1])
up95 = exp(log(HR) + qnorm(0.975)*sqrt(1/df1.survdiff$exp[2]+1/df1.survdiff$exp[1]))
low95 = exp(log(HR) - qnorm(0.975)*sqrt(1/df1.survdiff$exp[2]+1/df1.survdiff$exp[1]))
p.val = round(p.val, 4)
HR = round(HR, 2)
up95 = round(HR, 2)
low95 = round(low95, 2)
output.text = paste0("HR ", HR, "(95% CI ", low95,"-", up95, "); logrank p=", p.val)
p = ggsurvplot(fit, data = df1, conf.int = TRUE, risk.table = TRUE, break.x.by=48, legend = c(0.8,0.75)) +
  xlab("Time(h)")
p$table$labels$title = paste0("Number at risk(",output.text,")")
ggsave("4_1_1.png", plot = print(p), width = 12, height = 8, units = "in")
ggsave("4_1_1.pdf", plot = print(p), width = 12, height = 8, units = "in")
ggsave("4_1_1.tiff", plot = print(p), width = 12, height = 8, units = "in")
